version: '3'
networks:
  nginx:
    driver: bridge

services:

  app:
    image: likesistemas/php:latest
    container_name: nginx_app
    environment:
      - PHP_NAME=nginx_app
      - PHP_PM=dynamic
      - PHP_PM_MAX_CHILDREN=2
      - PHP_PM_START_SERVERS=1
      - PHP_PM_MIN_SPARE_SERVERS=1
      - PHP_PM_MAX_SPARE_SERVERS=1
      - PHP_PM_MAX_REQUESTS=500
    volumes:
      - ./www/:/var/www/public/
    networks:
      - nginx

  nginx_normal:
    image: likesistemas/nginx:dev
    build:
      context: .
      args: 
        - PHP_FPM_PASSWORD=$PHP_FPM_PASSWORD
    container_name: nginx_nginx
    environment:
      - HOST_PHP=nginx_app
      - PORTA_PHP=9000
    ports:
      - 83:80
    volumes:
      - ./www/:/var/www/public/
    links:
      - app
    depends_on:
      - app
    networks:
      - nginx

  nginx_rewrite:
    image: likesistemas/nginx:dev-rewrite
    build:
      context: .
      args: 
        - PHP_FPM_PASSWORD=$PHP_FPM_PASSWORD
    container_name: nginx_rewrite
    environment:
      - HOST_PHP=nginx_app
      - PORTA_PHP=9000
      - REWRITE=1
      - INDEX_FILE=rewrite.php
    ports:
      - 81:80
    volumes:
      - ./www/:/var/www/public/
    links:
      - app
    depends_on:
      - app
    networks:
      - nginx

  nginx_tryfiles:
    image: likesistemas/nginx:dev-tryfiles
    build:
      context: .
      args: 
        - PHP_FPM_PASSWORD=$PHP_FPM_PASSWORD
    container_name: nginx_tryfiles
    environment:
      - HOST_PHP=nginx_app
      - PORTA_PHP=9000
      - TRYFILES=1
      - INDEX_FILE=tryfiles.php
    ports:
      - 82:80
    volumes:
      - ./www/:/var/www/public/
    links:
      - app
    depends_on:
      - app
    networks:
      - nginx

  nginx_normal-extras:
    image: likesistemas/nginx:dev-extras
    build:
      context: .
      args: 
        - PHP_FPM_PASSWORD=$PHP_FPM_PASSWORD
    container_name: nginx_extras
    environment:
      - HOST_PHP=nginx_app
      - PORTA_PHP=9000
    ports:
      - 84:80
    volumes:
      - ./www/:/var/www/public/
      - ./.docker/nginx/conf.d/limit-requests.conf:/var/nginx/conf.d/limit-requests.conf
      - ./.docker/nginx/site.d/extras/:/var/nginx/site.d/extras/
    links:
      - app
    depends_on:
      - app
    networks:
      - nginx