networks:
  nginx:
    driver: bridge

services:

  app:
    image: likesistemas/php:latest
    container_name: nginx_app
    command: sleep 4
    environment:
      - PHP_NAME=nginx_app
      - PHP_PM=dynamic
      - PHP_PM_MAX_CHILDREN=2
      - PHP_PM_START_SERVERS=1
      - PHP_PM_MIN_SPARE_SERVERS=1
      - PHP_PM_MAX_SPARE_SERVERS=1
      - PHP_PM_MAX_REQUESTS=500
    volumes:
      - ./www/:/var/www/public/
    networks:
      - nginx

  nginx:
    image: likesistemas/nginx:dev
    build:
      context: .
      args: 
        - PHP_FPM_PASSWORD=${PHP_FPM_PASSWORD:-password}
    environment:
      - HOST_PHP=nginx_app
      - PORTA_PHP=9000
    ports:
      - 444:443
    volumes:
      - ./www/:/var/www/public/
      - ./.docker/ssl/:/var/www/ssl/
    links:
      - app
    depends_on:
      - app
    networks:
      - nginx