#!/bin/bash

start_nginx() {
	echo "Iniciando nginx...";
	exec nginx -c /var/www/nginx/nginx.conf -g 'daemon off;'
}

if [ -z "$PUBLIC_HTML" ]; then
	PUBLIC_HTML="/var/www/public/";
fi;

configure-nginx;

if [ -n "$HOST_PHP" ]; then
	dockerize \
		-wait tcp://${HOST_PHP}:${PORTA_PHP} \
		-timeout 10s \
	&& start_nginx
else
	start_nginx
fi