#!/bin/bash

start_nginx() {
	echo "Iniciando nginx...";
	exec nginx -c "${SRC_CONFIG}nginx.conf" -g 'daemon off;'
}

configure-nginx;
/docker-entrypoint.sh

if [ -n "$HOST_PHP" ]; then
	dockerize \
		-wait tcp://${HOST_PHP}:${PORTA_PHP} \
		-timeout ${TIMEOUT_PHP} \
	&& start_nginx
else
	start_nginx
fi